/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XncrButton {
        /**
          * @default false
         */
        "noiseAnim": boolean;
        "variant": string;
    }
    interface XncrInput {
        /**
          * @default ''
         */
        "button": string;
        /**
          * @default ''
         */
        "idOverride": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'side'
         */
        "labelPos": 'above' | 'side';
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readOnly": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface XncrTile {
        "clickable"?: boolean;
        /**
          * @default 'left'
         */
        "footerAlign": 'left' | 'center' | 'right';
        /**
          * @default 3
         */
        "headingLevel": 1 | 2 | 3 | 4 | 5;
        "href"?: string;
        "rel"?: string;
    }
}
export interface XncrInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXncrInputElement;
}
export interface XncrTileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXncrTileElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLXncrButtonElement extends Components.XncrButton, HTMLStencilElement {
    }
    var HTMLXncrButtonElement: {
        prototype: HTMLXncrButtonElement;
        new (): HTMLXncrButtonElement;
    };
    interface HTMLXncrInputElementEventMap {
        "clicked": PointerEvent;
    }
    interface HTMLXncrInputElement extends Components.XncrInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXncrInputElementEventMap>(type: K, listener: (this: HTMLXncrInputElement, ev: XncrInputCustomEvent<HTMLXncrInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXncrInputElementEventMap>(type: K, listener: (this: HTMLXncrInputElement, ev: XncrInputCustomEvent<HTMLXncrInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXncrInputElement: {
        prototype: HTMLXncrInputElement;
        new (): HTMLXncrInputElement;
    };
    interface HTMLXncrTileElementEventMap {
        "clicked": MouseEvent;
    }
    interface HTMLXncrTileElement extends Components.XncrTile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXncrTileElementEventMap>(type: K, listener: (this: HTMLXncrTileElement, ev: XncrTileCustomEvent<HTMLXncrTileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXncrTileElementEventMap>(type: K, listener: (this: HTMLXncrTileElement, ev: XncrTileCustomEvent<HTMLXncrTileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXncrTileElement: {
        prototype: HTMLXncrTileElement;
        new (): HTMLXncrTileElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "xncr-button": HTMLXncrButtonElement;
        "xncr-input": HTMLXncrInputElement;
        "xncr-tile": HTMLXncrTileElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XncrButton {
        /**
          * @default false
         */
        "noiseAnim"?: boolean;
        "variant"?: string;
    }
    interface XncrInput {
        /**
          * @default ''
         */
        "button"?: string;
        /**
          * @default ''
         */
        "idOverride"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'side'
         */
        "labelPos"?: 'above' | 'side';
        "name"?: string;
        "onClicked"?: (event: XncrInputCustomEvent<PointerEvent>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readOnly"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface XncrTile {
        "clickable"?: boolean;
        /**
          * @default 'left'
         */
        "footerAlign"?: 'left' | 'center' | 'right';
        /**
          * @default 3
         */
        "headingLevel"?: 1 | 2 | 3 | 4 | 5;
        "href"?: string;
        "onClicked"?: (event: XncrTileCustomEvent<MouseEvent>) => void;
        "rel"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "xncr-button": XncrButton;
        "xncr-input": XncrInput;
        "xncr-tile": XncrTile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "xncr-button": LocalJSX.XncrButton & JSXBase.HTMLAttributes<HTMLXncrButtonElement>;
            "xncr-input": LocalJSX.XncrInput & JSXBase.HTMLAttributes<HTMLXncrInputElement>;
            "xncr-tile": LocalJSX.XncrTile & JSXBase.HTMLAttributes<HTMLXncrTileElement>;
        }
    }
}
