/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XncrButton {
        /**
          * @default false
         */
        "noiseAnim": boolean;
        "variant": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLXncrButtonElement extends Components.XncrButton, HTMLStencilElement {
    }
    var HTMLXncrButtonElement: {
        prototype: HTMLXncrButtonElement;
        new (): HTMLXncrButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "xncr-button": HTMLXncrButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XncrButton {
        /**
          * @default false
         */
        "noiseAnim"?: boolean;
        "variant"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "xncr-button": XncrButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "xncr-button": LocalJSX.XncrButton & JSXBase.HTMLAttributes<HTMLXncrButtonElement>;
        }
    }
}
